# Generated by Django 5.0 on 2023-12-31 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudent',
            name='college_student_id',
        ),
        migrations.RemoveField(
            model_name='schoolstudent',
            name='school_student_id',
        ),
    ]
