# Generated by Django 5.0 on 2024-01-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_bothteacher_id_alter_collegeteacher_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bothteacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collegeteacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoolteacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
