# Generated by Django 5.0 on 2024-01-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_bothteacher_id_alter_collegeteacher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudent',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='collegestudent',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='schoolstudent',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='schoolstudent',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoolstudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
